blank_issues_enabled: false
contact_links:
  - name: Questions & Support Requests
    url: https://github.com/GatewayQL/nest-GatewayQL/discussions
    about: Ask questions and get support from the community
  - name: Security Vulnerability
    url: https://github.com/GatewayQL/nest-GatewayQL/security/advisories/new
    about: Report a security vulnerability privately
  - name: Documentation
    url: https://gatewayql.github.io/nest-GatewayQL
    about: Read the official documentation
